/*
 * Real 4x4 state solver: painted stickers → TNoodle three-phase reduction
 * (vendored from cubing.js via scripts/patch-cubing-444.mjs) → verified 3x3
 * finish → parity fixes with our machine-verified algorithms.
 *
 * Nothing about TNoodle's internal numbering is assumed: at init we drive its
 * move functions and our geometric facelet simulator in tandem and LEARN
 * every mapping (position ↔ sticker cells, colors ↔ piece/orientation) by
 * observation. Every solve ends with a hard check — the full move sequence
 * applied to the input stickers must leave all six faces uniform — so a
 * wrong answer can never be displayed.
 */
import {
  applyMoves4,
  labeledFacelets4,
  stickerPositions4,
  isUniform4,
  type Facelets4,
} from "./faceletsNxN.ts";
const FACE_NAMES = ["U", "L", "F", "R", "B", "D"];

/* OLL/PLL parity — the exact algorithms machine-verified in verify-algs.mjs. */
const OLL_PARITY = "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'";
const PLL_PARITY = "2R2 U2 2R2 Uw2 2R2 2U2";

interface TN {
  FullCube_3: new () => TNCube;
  Search_4: new () => TNSearch;
  $doSearch: (s: TNSearch) => void;
  move2str_1: string[];
  symmove: number[][];
  symmult: number[][];
  move2rot: number[];
  moveFns: {
    center: (o: unknown, m: number) => void;
    edge: (o: unknown, m: number) => void;
    corner: (o: unknown, m: number) => void;
    cornerMax: number;
  };
}
interface TNCube {
  center: { ct: number[] };
  edge: { ep: number[] };
  corner: { cp: number[]; co: number[] };
}
interface TNSearch {
  c: TNCube;
  solution: string;
  solcube: {
    moveBuffer: number[];
    moveLength: number;
    length1: number;
    add1: boolean;
    sym: number;
  };
}

interface Calibration {
  tn: TN;
  moveTokens: string[]; // token per TN move index
  centerCellOf: number[]; // TN center pos -> flat cell index
  tnClassToFace: number[]; // TN center class -> our face index
  faceToTnClass: number[]; // our face index -> TN center class
  wingCellsOf: [number, number][]; // TN wing pos -> canonical cell pair
  cornerCellsOf: [number, number, number][]; // TN corner pos -> cell triple
  wingDict: Map<string, number[]>; // `${pos}:${c1},${c2}` -> candidate piece ids
  cornerDict: Map<string, { piece: number; co: number }>;
  reductionIsCreation: boolean | null; // does $doSearch return state-creation moves?
}

let calibrationPromise: Promise<Calibration> | null = null;

const flatten = (f: Facelets4) => f.flat();
const classOfLabel = (label: number) => Math.floor(label / 16);

function applyTN(tn: TN, cube: TNCube, m: number) {
  tn.moveFns.center(cube.center, m);
  tn.moveFns.edge(cube.edge, m);
  // wide moves act on corners like their outer counterpart
  tn.moveFns.corner(cube.corner, m < tn.moveFns.cornerMax ? m : m - 18);
}

/** A(i): TN position -> entity index, from labeled-generator conjugacy. */
function solveConjugacy(n: number, sigmaTN: number[][], sigmaSIM: number[][]): number[] {
  outer: for (let seed = 0; seed < n; seed++) {
    const A = new Array<number>(n).fill(-1);
    A[0] = seed;
    const queue = [0];
    const used = new Set([seed]);
    while (queue.length) {
      const i = queue.pop()!;
      for (let m = 0; m < sigmaTN.length; m++) {
        const j = sigmaTN[m][i];
        const want = sigmaSIM[m][A[i]];
        if (A[j] === -1) {
          if (used.has(want)) continue outer;
          A[j] = want;
          used.add(want);
          queue.push(j);
        } else if (A[j] !== want) {
          continue outer;
        }
      }
    }
    if (A.every((v) => v !== -1)) return A;
  }
  throw new Error("4x4 solver: conjugacy calibration failed");
}

async function calibrate(): Promise<Calibration> {
  // Generated by scripts/patch-cubing-444.mjs at postinstall; untyped GWT output.
  // @ts-expect-error -- no declaration file for the generated shim
  const internals = (await import("../generated/solve444-internals.js")) as Record<string, unknown>;
  (internals.initialize as () => void)();
  const move2str = internals.move2str_1 as string[];
  const moveTokens = move2str.map((s) => s.trim());

  // Identify which $move variant drives which piece array, by probing.
  // Snapshots compare only the state arrays — some move functions lazily
  // attach scratch fields (e.g. CornerCube.temps) that must not count.
  const mk = () => new (internals.FullCube_3 as new () => TNCube)();
  const candidates = ["$move", "$move_0", "$move_1", "$move_2", "$move_3", "$move_4", "$move_5"]
    .map((k) => internals[k])
    .filter(Boolean) as ((o: unknown, m: number) => void)[];
  const snap = (sub: "center" | "edge" | "corner", cube: TNCube) =>
    JSON.stringify(
      sub === "center" ? cube.center.ct : sub === "edge" ? cube.edge.ep : [cube.corner.cp, cube.corner.co],
    );
  // Outer turns permute identical-class center values invisibly, so centers
  // are probed with a wide move.
  const probeMove = (sub: string) => (sub === "center" ? 18 : 3);
  const probeAll = (sub: "center" | "edge" | "corner") => {
    const found: ((o: unknown, m: number) => void)[] = [];
    for (const fn of candidates) {
      try {
        const cube = mk();
        const before = snap(sub, cube);
        const m = probeMove(sub);
        fn(cube[sub], m);
        if (snap(sub, cube) !== before) {
          for (let t = 0; t < 3; t++) fn(cube[sub], m);
          if (snap(sub, cube) === before) found.push(fn);
        }
      } catch {
        // wrong class for this function — keep probing
      }
    }
    if (found.length === 0) throw new Error(`4x4 solver: no move function found for ${sub}`);
    return found;
  };
  const centerFns = probeAll("center");
  const edgeFn = probeAll("edge")[0];
  const cornerFn = probeAll("corner")[0];
  // If several center candidates exist, keep those whose effects agree; any
  // disagreement is resolved by which one calibrates successfully below.
  const centerFn = centerFns[0];
  // How many move indices do corners support? (wide moves may be outer-only)
  let cornerMax = 36;
  try {
    const cube = mk();
    cornerFn(cube.corner, 18);
  } catch {
    cornerMax = 18;
  }
  const tn: TN = {
    FullCube_3: internals.FullCube_3 as TN["FullCube_3"],
    Search_4: internals.Search_4 as TN["Search_4"],
    $doSearch: internals.$doSearch as TN["$doSearch"],
    move2str_1: move2str,
    symmove: internals.symmove as number[][],
    symmult: internals.symmult as number[][],
    move2rot: internals.move2rot as number[],
    moveFns: { center: centerFn, edge: edgeFn, corner: cornerFn, cornerMax },
  };

  // ——— Geometry: entities on our side ———
  const positions = stickerPositions4();
  const centerCells: number[] = [];
  const cornerCellIdx: number[] = [];
  const edgeCellIdx: number[] = [];
  for (let i = 0; i < 96; i++) {
    const cell = i % 16;
    const r = Math.floor(cell / 4);
    const c = cell % 4;
    const rc = (v: number) => v === 0 || v === 3;
    if (!rc(r) && !rc(c)) centerCells.push(i);
    else if (rc(r) && rc(c)) cornerCellIdx.push(i);
    else edgeCellIdx.push(i);
  }
  const d2 = (a: number, b: number) => {
    const p = positions[a];
    const q = positions[b];
    return (p[0] - q[0]) ** 2 + (p[1] - q[1]) ** 2 + (p[2] - q[2]) ** 2;
  };
  // wings pair across a cube edge (distance² = 2), corners triple around a vertex
  const wingPairs: [number, number][] = [];
  {
    const usedW = new Set<number>();
    for (const a of edgeCellIdx) {
      if (usedW.has(a)) continue;
      const partner = edgeCellIdx.find((b) => b !== a && !usedW.has(b) && d2(a, b) === 2);
      if (partner === undefined) throw new Error("4x4 solver: wing pairing failed");
      usedW.add(a);
      usedW.add(partner);
      wingPairs.push(a < partner ? [a, partner] : [partner, a]);
    }
  }
  const cornerTriples: [number, number, number][] = [];
  {
    const usedC = new Set<number>();
    for (const a of cornerCellIdx) {
      if (usedC.has(a)) continue;
      const mates = cornerCellIdx.filter((b) => b !== a && !usedC.has(b) && d2(a, b) === 2);
      if (mates.length !== 2) throw new Error("4x4 solver: corner grouping failed");
      usedC.add(a);
      for (const m of mates) usedC.add(m);
      cornerTriples.push([a, mates[0], mates[1]].sort((x, y) => x - y) as [number, number, number]);
    }
  }
  const pairIndexByCell = new Map<number, number>();
  wingPairs.forEach((p, idx) => p.forEach((c) => pairIndexByCell.set(c, idx)));
  const tripleIndexByCell = new Map<number, number>();
  cornerTriples.forEach((t, idx) => t.forEach((c) => tripleIndexByCell.set(c, idx)));

  // ——— Single-move permutations, both engines ———
  const simMovePerm = moveTokens.map((token) => {
    const labels = flatten(applyMoves4(labeledFacelets4(), token));
    return labels;
  });
  const sigmaSIMWing = simMovePerm.map((labels) => {
    // pair entity -> pair entity: where did pair p's cells go?
    const dest = new Array<number>(wingPairs.length).fill(-1);
    const cellDest = new Array<number>(96);
    labels.forEach((label, cell) => (cellDest[label] = cell));
    wingPairs.forEach(([a], p) => (dest[p] = pairIndexByCell.get(cellDest[a])!));
    return dest;
  });
  const sigmaSIMCorner = simMovePerm.map((labels) => {
    const cellDest = new Array<number>(96);
    labels.forEach((label, cell) => (cellDest[label] = cell));
    return cornerTriples.map(([a]) => tripleIndexByCell.get(cellDest[a])!);
  });
  const sigmaTNWing: number[][] = [];
  const sigmaTNCorner: number[][] = [];
  for (let m = 0; m < moveTokens.length; m++) {
    const cube = mk();
    applyTN(tn, cube, m);
    const wing = new Array<number>(24);
    cube.edge.ep.forEach((piece, pos) => (wing[piece] = pos));
    sigmaTNWing.push(wing);
    const corner = new Array<number>(8);
    cube.corner.cp.forEach((piece, pos) => (corner[piece] = pos));
    sigmaTNCorner.push(corner);
  }
  const wingA = solveConjugacy(24, sigmaTNWing, sigmaSIMWing);
  const cornerA = solveConjugacy(8, sigmaTNCorner, sigmaSIMCorner);
  const wingCellsOf = wingA.map((e) => wingPairs[e]);
  const cornerCellsOf = cornerA.map((e) => cornerTriples[e]);

  // ——— Sampling: centers by value-intersection; piece/orientation dictionaries ———
  let seed = 0x444;
  const rand = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff), seed / 0x7fffffff);
  // TNoodle's center class numbering need not match our face order — for
  // each (position, candidate cell) we track the tnClass→simClass relation
  // and keep only candidates where it stays a function.
  const centerRel: (Map<number, number> | null)[][] = Array.from({ length: 24 }, () =>
    centerCells.map(() => new Map<number, number>()),
  );
  const wingDict = new Map<string, number[]>();
  const cornerDict = new Map<string, { piece: number; co: number }>();
  const wingSeen = new Set<string>();
  for (let round = 0; round < 400; round++) {
    const len = 30;
    const cube = mk();
    let labels = labeledFacelets4();
    for (let k = 0; k < len; k++) {
      const m = Math.floor(rand() * moveTokens.length);
      applyTN(tn, cube, m);
      labels = applyMoves4(labels, moveTokens[m]);
    }
    const flat = flatten(labels);
    // centers: candidate survives while (tnClass → simClass) stays functional
    for (let pos = 0; pos < 24; pos++) {
      const tnClass = cube.center.ct[pos];
      for (let ci = 0; ci < centerCells.length; ci++) {
        const rel = centerRel[pos][ci];
        if (!rel) continue;
        const simClass = classOfLabel(flat[centerCells[ci]]);
        const prev = rel.get(tnClass);
        if (prev === undefined) rel.set(tnClass, simClass);
        else if (prev !== simClass) centerRel[pos][ci] = null;
      }
    }
    // wings: observed colors at a position -> piece id
    for (let pos = 0; pos < 24; pos++) {
      const [a, b] = wingCellsOf[pos];
      const key = `${pos}:${classOfLabel(flat[a])},${classOfLabel(flat[b])}`;
      const piece = cube.edge.ep[pos];
      if (!wingSeen.has(`${key}=${piece}`)) {
        wingSeen.add(`${key}=${piece}`);
        wingDict.set(key, [...(wingDict.get(key) ?? []), piece]);
      }
    }
    // corners
    for (let pos = 0; pos < 8; pos++) {
      const [a, b, c] = cornerCellsOf[pos];
      const key = `${pos}:${classOfLabel(flat[a])},${classOfLabel(flat[b])},${classOfLabel(flat[c])}`;
      const entry = { piece: cube.corner.cp[pos], co: cube.corner.co[pos] };
      const prev = cornerDict.get(key);
      if (prev && (prev.piece !== entry.piece || prev.co !== entry.co)) {
        throw new Error("4x4 solver: corner dictionary conflict");
      }
      cornerDict.set(key, entry);
    }
  }
  // Resolve center assignment + the global class bijection π together.
  const tnClassToFace = new Array<number>(6).fill(-1);
  const centerCellOf = new Array<number>(24).fill(-1);
  {
    const survivors = centerRel.map((rels, pos) =>
      rels
        .map((rel, ci) => (rel ? { ci, rel } : null))
        .filter((x): x is { ci: number; rel: Map<number, number> } => x !== null && x.rel.size >= 4)
        .map((x) => ({ ...x, pos })),
    );
    const order = Array.from({ length: 24 }, (_, i) => i).sort(
      (a, b) => survivors[a].length - survivors[b].length,
    );
    const usedCell = new Set<number>();
    const assign = (k: number): boolean => {
      if (k === 24) return true;
      const pos = order[k];
      for (const { ci, rel } of survivors[pos]) {
        const cell = centerCells[ci];
        if (usedCell.has(cell)) continue;
        // must be consistent with the partial bijection π
        const touched: number[] = [];
        let ok = true;
        for (const [tnC, simC] of rel) {
          if (tnClassToFace[tnC] === -1) {
            if (tnClassToFace.includes(simC)) {
              ok = false;
              break;
            }
            tnClassToFace[tnC] = simC;
            touched.push(tnC);
          } else if (tnClassToFace[tnC] !== simC) {
            ok = false;
            break;
          }
        }
        if (ok) {
          usedCell.add(cell);
          centerCellOf[pos] = cell;
          if (assign(k + 1)) return true;
          usedCell.delete(cell);
          centerCellOf[pos] = -1;
        }
        for (const t of touched) tnClassToFace[t] = -1;
      }
      return false;
    };
    if (!assign(0)) throw new Error("4x4 solver: center calibration failed");
  }

  return {
    tn,
    moveTokens,
    centerCellOf,
    tnClassToFace,
    faceToTnClass: tnClassToFace.map((_, f) => tnClassToFace.indexOf(f)),
    wingCellsOf,
    cornerCellsOf,
    wingDict,
    cornerDict,
    reductionIsCreation: null,
  };
}

export function initSolver4x4(): Promise<Calibration> {
  calibrationPromise ??= calibrate();
  return calibrationPromise;
}

export interface Solve4Result {
  ok: boolean;
  solution?: string;
  moveCount?: number;
  errors: string[];
}

function validate(colors: Facelets4): string[] {
  const errors: string[] = [];
  const counts = Array.from({ length: 6 }, () => 0);
  for (const face of colors) for (const c of face) counts[c]++;
  counts.forEach((n, c) => {
    if (n !== 16) errors.push(`Needs exactly 16 ${FACE_NAMES[c]}-color stickers, found ${n}.`);
  });
  return errors;
}

/** Encode painted colors into a TNoodle FullCube. */
function encode(cal: Calibration, colors: Facelets4): { cube?: TNCube; errors: string[] } {
  const flat = flatten(colors);
  const errors = validate(colors);
  if (errors.length) return { errors };

  const cube = new cal.tn.FullCube_3();
  for (let pos = 0; pos < 24; pos++) {
    cube.center.ct[pos] = cal.faceToTnClass[flat[cal.centerCellOf[pos]]];
  }

  // wings: candidates per position, then perfect-matching (twins are
  // visually identical, so any consistent assignment is correct)
  const candidates: number[][] = [];
  for (let pos = 0; pos < 24; pos++) {
    const [a, b] = cal.wingCellsOf[pos];
    const key = `${pos}:${flat[a]},${flat[b]}`;
    const c = cal.wingDict.get(key);
    if (!c || c.length === 0) {
      errors.push(`An edge piece near the ${FACE_NAMES[Math.floor(a / 16)]} face shows an impossible color combination.`);
      candidates.push([]);
    } else {
      candidates.push(c);
    }
  }
  if (errors.length) return { errors };
  const assigned = new Array<number>(24).fill(-1);
  const usedPiece = new Array<boolean>(24).fill(false);
  const order = Array.from({ length: 24 }, (_, i) => i).sort(
    (x, y) => candidates[x].length - candidates[y].length,
  );
  const backtrack = (k: number): boolean => {
    if (k === 24) return true;
    const pos = order[k];
    for (const piece of candidates[pos]) {
      if (usedPiece[piece]) continue;
      usedPiece[piece] = true;
      assigned[pos] = piece;
      if (backtrack(k + 1)) return true;
      usedPiece[piece] = false;
      assigned[pos] = -1;
    }
    return false;
  };
  if (!backtrack(0)) {
    return { errors: ["The edge pieces don't form a possible cube — re-check for two mixed-up stickers."] };
  }
  for (let pos = 0; pos < 24; pos++) cube.edge.ep[pos] = assigned[pos];

  for (let pos = 0; pos < 8; pos++) {
    const [a, b, c] = cal.cornerCellsOf[pos];
    const key = `${pos}:${flat[a]},${flat[b]},${flat[c]}`;
    const entry = cal.cornerDict.get(key);
    if (!entry) {
      errors.push("A corner shows an impossible color combination — re-check its three stickers.");
      continue;
    }
    cube.corner.cp[pos] = entry.piece;
    cube.corner.co[pos] = entry.co;
  }
  if (errors.length) return { errors };
  if (new Set(cube.corner.cp).size !== 8) {
    return { errors: ["Two corners have identical colors — one of them is painted wrong."] };
  }
  if (cube.corner.co.reduce((x, y) => x + y, 0) % 3 !== 0) {
    return { errors: ["A corner is twisted — this state is unsolvable. Re-check corner colors."] };
  }
  return { cube, errors: [] };
}

/**
 * Extract the SOLVING-direction reduction sequence from the raw search
 * buffer. TNoodle records phase-1 moves in the global frame and phase-2/3
 * moves in ONE whole-cube-rotated frame (its printer re-expresses them via
 * implicit rotations — fine for scrambles, wrong for solving). Instead of
 * reverse-engineering its symmetry tables, we recover the frame empirically:
 * the physical sequence is  phase1 · r₀ · phase23 · r₀⁻¹  for one of the 24
 * cube rotations, and the simulator tells us which one in microseconds.
 */
const ROT24: string[] = [];
for (const a of ["", "x", "x2", "x'", "z", "z'"]) {
  for (const b of ["", "y", "y2", "y'"]) {
    ROT24.push([a, b].filter(Boolean).join(" "));
  }
}
const invertRotation = (r: string) =>
  r
    .split(" ")
    .filter(Boolean)
    .reverse()
    .map((t) => (t.endsWith("'") ? t.slice(0, -1) : t.endsWith("2") ? t : `${t}'`))
    .join(" ");

function reductionMoves(cal: Calibration, cube: TNCube, colors: Facelets4): string | null {
  const searcher = new cal.tn.Search_4();
  searcher.c = cube;
  cal.tn.$doSearch(searcher);
  const sc = searcher.solcube;
  const phase1 = sc.moveBuffer.slice(0, sc.length1).map((m) => cal.moveTokens[m]);
  for (const skipAdd1 of sc.add1 ? [true, false] : [false]) {
    const rest = sc.moveBuffer
      .slice(sc.length1 + (skipAdd1 ? 2 : 0), sc.moveLength)
      .map((m) => cal.moveTokens[m]);
    for (const r0 of ROT24) {
      const seq = [...phase1, r0, ...rest, invertRotation(r0)].filter(Boolean).join(" ");
      if (dedgesPaired(applyMoves4(colors, seq))) return seq;
    }
  }
  return null;
}

/** Reduced = every face's center block uniform and every dedge's wings matching. */
function dedgesPaired(f: Facelets4): boolean {
  for (let face = 0; face < 6; face++) {
    const centers = [5, 6, 9, 10].map((c) => f[face][c]);
    if (new Set(centers).size !== 1) return false;
  }
  // Adjacent wing cells on each face edge must show equal colors per dedge:
  // check via geometry: for every face, the two middle cells of each border
  // row/column belong to the two wings of one dedge.
  for (let face = 0; face < 6; face++) {
    const rows = [
      [f[face][1], f[face][2]],
      [f[face][13], f[face][14]],
      [f[face][4], f[face][8]],
      [f[face][7], f[face][11]],
    ];
    for (const [a, b] of rows) if (a !== b) return false;
  }
  return true;
}

/** Map a reduced 4x4 to 3x3 facelets, normalizing colors so centers read 0–5. */
function reducedTo3x3(f: Facelets4): number[][] {
  const colorMap = new Map<number, number>();
  f.forEach((face, faceIdx) => colorMap.set(face[5], faceIdx));
  if (colorMap.size !== 6) throw new Error("reduced state has duplicate center colors");
  // Representative 4x4 cell per 3x3 cell: corners from corners, edges from
  // one of the pair (dedgesPaired guarantees they agree), centers from block.
  const cell4 = (face: number, r3: number, c3: number): number => {
    const r = r3 === 0 ? 0 : r3 === 1 ? 1 : 3;
    const c = c3 === 0 ? 0 : c3 === 1 ? 1 : 3;
    return f[face][r * 4 + c];
  };
  const out: number[][] = [];
  for (let face = 0; face < 6; face++) {
    const cells: number[] = [];
    for (let r = 0; r < 3; r++) {
      for (let c = 0; c < 3; c++) cells.push(colorMap.get(cell4(face, r, c))!);
    }
    cells[4] = face;
    out.push(cells);
  }
  return out;
}

/**
 * Solve a painted 4x4. Returns a full move sequence (reduction + parity
 * fixes + 3x3 stage) that is verified against the simulator before being
 * returned — an unverified sequence is never shown.
 */
export async function solve4x4(colors: Facelets4): Promise<Solve4Result> {
  const cal = await initSolver4x4();
  const { cube, errors } = encode(cal, colors);
  if (!cube) return { ok: false, errors };

  const seq = reductionMoves(cal, cube, colors);
  if (seq === null) {
    return { ok: false, errors: ["The 4x4 engine couldn't reduce this state — re-check your stickers."] };
  }

  let working = applyMoves4(colors, seq);
  let solution = seq;
  // 3x3 stage with parity retries
  const [{ cube3x3x3 }, { experimentalSolve3x3x3IgnoringCenters }, lib3] = await Promise.all([
    import("cubing/puzzles"),
    import("cubing/search"),
    import("./facelets3x3.ts"),
  ]);
  const kpuzzle = await cube3x3x3.kpuzzle();
  await lib3.initFaceletEngine(kpuzzle);
  for (let attempt = 0; attempt < 4; attempt++) {
    let mapped: number[][];
    try {
      mapped = reducedTo3x3(working);
    } catch {
      return { ok: false, errors: ["Reduction produced an inconsistent state — please report this."] };
    }
    const built = lib3.faceletsToPattern(kpuzzle, mapped);
    if (built.ok && built.pattern) {
      const tail = (await experimentalSolve3x3x3IgnoringCenters(built.pattern)).toString();
      let full = `${solution} ${tail}`.trim().replace(/\s+/g, " ");
      const finalState = applyMoves4(colors, full);
      if (!isUniform4(finalState)) {
        return { ok: false, errors: ["Internal verification failed — no solution shown. Please report this state."] };
      }
      // Orientation-normalize the finish: append the whole-cube rotation that
      // lands on the standard scheme (white up, green front). This makes the
      // twisty player's inverse-anchored preview show the PAINTED state
      // exactly, instead of a rotated frame the user never held.
      const canonical = (f: Facelets4) => f.every((face, i) => face[0] === i);
      if (!canonical(finalState)) {
        for (const r of ROT24) {
          if (r && canonical(applyMoves4(finalState, r))) {
            full = `${full} ${r}`;
            break;
          }
        }
      }
      return { ok: true, solution: full, moveCount: full.split(" ").length, errors: [] };
    }
    const text = built.errors.join(" ");
    if (text.includes("flipped")) {
      solution = `${solution} ${OLL_PARITY}`;
      working = applyMoves4(working, OLL_PARITY);
    } else if (text.includes("swapped")) {
      solution = `${solution} ${PLL_PARITY}`;
      working = applyMoves4(working, PLL_PARITY);
    } else {
      return { ok: false, errors: built.errors };
    }
  }
  return { ok: false, errors: ["Couldn't resolve parity for this state — please report it."] };
}

/** Test/verify hooks — not part of the app surface. */
export const __test = { encode, reductionMoves, dedgesPaired };
